# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-08-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
