---
- name: Create and manage venv
  hosts: all
  vars:
    HOST: "{{ inventory_hostname }}"
    ROOT_FOLDER: "~/sites/{{ HOST }}"
  tasks:
     - name: create a virtual environment in the superlists site
       command: python3 -m venv "{{ ROOT_FOLDER }}/sample_venv"

     - name: Install the project required python packages
       pip:
         executable: "{{ ROOT_FOLDER }}/sample_venv/bin/pip"
         requirements: "{{ ROOT_FOLDER }}/requirements.txt"
...
