---
- name: Get latest commit from github
  hosts: all

  vars: 
    HOST: "{{ inventory_hostname}}"
    REPO_URL: "https://github.com/kevinbeirne1/tdd_with_python.git"
    ROOT_FOLDER: "~/sites/{{ HOST }}"

  tasks:

     - name: clone latest version from from git
       ansible.builtin.git:
         repo: "{{ REPO_URL }}"
         dest: "{{ ROOT_FOLDER }}"
         single_branch: yes
         version: main
         force: yes

...
