---
- name: My task
  hosts: all
  vars: 
    USER: "{{ lookup('env', 'USER') }}"
    HOST: "superlists-staging"
    REPO_URL: "https://github.com/kevinbeirne1/tdd_with_python.git"
    SITE_FOLDER: "~/sites/{{ HOST }}.kbeirne.com"
  tasks:
     - name: print variables
       debug:
         msg: "{{ USER }}@{{ HOST }}.kbeirne.com"

     - name: get latest git commit
       shell: chdir={{ SITE_FOLDER }} git log -n 1 --format=%H
       register: latest_commit

     - name: log latest commit to file
       shell: echo {{ latest_commit['stdout'] }}

     - name: clone latest version from from git
       ansible.builtin.git:
         repo: "{{ REPO_URL }}"
         dest: "{{ SITE_FOLDER }}/test"
         single_branch: yes
         version: main

...
