---
- name: Create and manage venv
  hosts: all
  vars:
    HOST: "{{ inventory_hostname }}"
    ROOT_FOLDER: "~/sites/{{ HOST }}"
    VIRTUAL_ENV_FOLDER: '{{ ROOT_FOLDER }}/virtualenv'
    PYTHON_EXECUTABLE: '{{ VIRTUAL_ENV_FOLDER }}/bin/python'

  tasks:
    - name: check if virtual environment exists
      stat:
        path: "{{ PYTHON_EXECUTABLE }}"
      register: stat_result

    - name: create a virtual environment in the root folder
      command: python3 -m venv "{{ ROOT_FOLDER }}/virtualenv"
      when: not stat_result.stat.exists

    - name: Install the python packages for the project
      pip:
       executable: "{{ ROOT_FOLDER }}/virtualenv/bin/pip"
       requirements: "{{ ROOT_FOLDER }}/requirements.txt"
...
