---
- name: Create .env and set Django security variables
  hosts: all
  vars:
      HOST: '{{ inventory_hostname }}'
      ROOT_FOLDER: '~/sites/{{ HOST }}'
      DOT_ENV_FILE: "{{ ROOT_FOLDER }}/.env"
      VIRTUAL_ENV_FOLDER: '{{ ROOT_FOLDER }}/virtualenv'
      PYTHON_EXECUTABLE: '{{ VIRTUAL_ENV_FOLDER }}/bin/python'

  tasks:
    - name: ensure .env exists
      command: "touch {{ DOT_ENV_FILE }}"

    - name: run get_secret_key script
      command:
        argv:
          - "{{ PYTHON_EXECUTABLE }}"
          - "{{ ROOT_FOLDER }}/deploy_tools/get_secret_key.py"
      register: secret_key

    - name: Verify DJANGO_SECRET_KEY present
      lineinfile:
          path: '{{ DOT_ENV_FILE }}'
          regexp: "^DJANGO_SECRET_KEY="
          line: "{{ secret_key['stdout_lines'][0] }}"

    - name: Verify DJANGO_DEBUG_FALSE set to y
      lineinfile:
          path: '{{ DOT_ENV_FILE }}'
          line: 'DJANGO_DEBUG_FALSE=y'

    - name: Verify SITENAME is set
      lineinfile:
          path: '{{ DOT_ENV_FILE }}'
          line: 'SITENAME={{ HOST }}'

...
