---
- name: Create .env and set Django security variables
  hosts: all
  vars:
      PATH: "/home/.env"
      SECRET_KEY: "ct_&ev##lvga&gh7#qr^yd=gr4&^*#mu)$ej_%$=qf7@cr-8zy"
      HOST: '{{ inventory_hostname }}'
      ROOT_FOLDER: '~/sites/{{ HOST }}'
      VIRTUAL_ENV_FOLDER: '{{ ROOT_FOLDER }}/virtualenv'

  tasks:
    - name: run get_secret_key script
      script: "./get_secret_key.py"
      args:
        executable: "{{ VIRTUAL_ENV_FOLDER }}/bin/python"
      register: secret_key

    - name: Print result of get_secret_key
      lineinfile:
          path: '{{ PATH }}'
          line: "{{ secret_key['stdout_lines'][0] }}"
      become: yes
      become_method: sudo
#      debug:
#        msg: "{{ secret_key }}"

    - name: Verify DJANGO_DEBUG_FALSE set to y
      lineinfile:
          path: '{{ PATH }}'
          line: 'DJANGO_DEBUG_FALSE=y'
      become: yes
      become_method: sudo

    - name: Verify SITENAME is set
      lineinfile:
          path: '{{ PATH }}'
          line: 'SITENAME={{ HOST }}'
      become: yes
      become_method: sudo

...
