---
- name: Create .env and set Django security variables
  hosts: all
  vars:
      PATH: "/home/.env"
      SECRET_KEY: "ct_&ev##lvga&gh7#qr^yd=gr4&^*#mu)$ej_%$=qf7@cr-8zy"
      HOST: '{{ inventory_hostname }}'
      ROOT_FOLDER: '~/sites/{{ HOST }}'
      VIRTUAL_ENV_FOLDER: '{{ ROOT_FOLDER }}/virtualenv'
      PYTHON_EXECUTABLE: '{{ VIRTUAL_ENV_FOLDER }}/bin/python'

  tasks:
    - name: ensure .env exists
      command: "touch {{ ROOT_FOLDER }}/.env"

    - name: run get_secret_key script
      script: "./get_secret_key.py"
      args:
        executable: "{{ PYTHON_EXECUTABLE }}"
      register: secret_key

    - name: Verify DJANGO_SECRET_KEY present
      lineinfile:
          regexp: "^DJANGO_SECRET_KEY="
          path: '{{ PATH }}'
          line: "{{ secret_key['stdout_lines'][0] }}"
      become: yes
      become_method: sudo

    - name: Verify DJANGO_DEBUG_FALSE set to y
      lineinfile:
          path: '{{ PATH }}'
          line: 'DJANGO_DEBUG_FALSE=y'
      become: yes
      become_method: sudo

    - name: Verify SITENAME is set
      lineinfile:
          path: '{{ PATH }}'
          line: 'SITENAME={{ HOST }}'
      become: yes
      become_method: sudo

...
